name = "base64-util"
compatibility_date = "2024-01-01"

[build]
command = "npm run build && npm run pages:build"
cwd = ""
watch_dir = ""

[env.production]
name = "base64-util"

[env.preview]
name = "base64-util-preview"
